### ISSUE TITLE
Stage Logs (Deliver)

### ISSUE THREAD

**Issue by sandtornado** [jenkins-docs/simple-java-maven-app#163]
when i run the project on a docker jenkins  ,a error has be found in the step of "Deliver" , error below
________________________________________________________________
Pipeline] { (Deliver)
[Pipeline] sh
+ ./jenkins/scripts/deliver.sh
/var/jenkins_home/workspace/simple-java-maven-app@tmp/durable-d387edf0/script.sh: line 1: ./jenkins/scripts/deliver.sh: Permission denied

**Comment by cenwei1234** [comment]
Hi,I have solved,modify jenkinfile sh 'bash ./jenkins/scripts/deliver.sh'
