### ISSUE TITLE
java.lang.NoSuchMethodError: No such DSL method 'get' found among steps [archive, bat, b

### ISSUE THREAD

**Issue by vivekdevopshub** [jenkins-docs/simple-java-maven-app#172]
Hi ,

I am facing this error while doing build for my pipeline job.

java.lang.NoSuchMethodError: No such DSL method 'get' found among steps [archive, bat, build, catchError, checkout, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, emailext, emailextrecipients, envVarsForTool, error, fileExists, findBuildScans, getContext, git, input, isUnix, junit, library, libraryResource, load, lock, mail, milestone, node, parallel, powershell, properties, pwd, pwsh, readFile, readTrusted, resolveScm, retry, script, sh, sleep, stage, stash, step, svn, timeout, timestamps, tm, tool, unarchive, unstable, unstash, validateDeclarativePipeline, waitUntil, warnError, withContext, withCredentials, withDockerContainer, withDockerRegistry, withDockerServer, withEnv, withGradle, wrap, writeFile, ws] or symbols [all, allOf, always, ant, antFromApache,

**Comment by MarkEWaite** [comment]
There is no location in the instructions that uses `get` as a Pipeline step.  Check that you've followed the instructions precisely
