### ISSUE TITLE
Source option 6 is no longer supported. Use 7 or later

### ISSUE THREAD

**Issue by romarknmsu** [jenkins-docs/simple-java-maven-app#282]
I attempted to run this in Jenkins and it returned this error. Any idea on how to fix? 

`[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.842 s
[INFO] Finished at: 2021-06-15T12:38:35-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project my-app: Compilation failure: Compilation failure: 
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE`

**Comment by hrb1989** [comment]
I have submitted a PR to resolve this error. Please have a check on the same. https://github.com/jenkins-docs/simple-java-maven-app/pull/297

the issue is in the pom.xml file. Add the following line:

https://github.com/jenkins-docs/simple-java-maven-app/blob/9cc1a5590b4fa6db01881d225fafa31e29be4bd1/pom.xml#L10

**Comment by DesmondWasHere** [comment]
Just update pom.xml
<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.1</version>
</plugin>
