### ISSUE TITLE
Failure to pass unit test. Maven version issue

### ISSUE THREAD

**Issue by CPaxtonProgrammer** [jenkins-docs/simple-java-maven-app#506]
My pipeline failed the Unit tests due to exit code 1. I think I followed the instructions carefully, I have the latest version of Maven installed, yet my app cannot pass the unit tests because the maven-enforcer-plugin says my version 3.6.3  is not in the allowed range of 3.8.6.

My declarative pipeline code is:
`pipeline {
    agent any
    stages {
       stage("Clean Up") {
           steps{
               deleteDir()
           }
       }
       stage("Clone Repo"){
           steps {
               sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
           }
       }
       stage("Build"){
           steps {
               dir("simple-java-maven-app") {
                   sh "mvn clean install"
               }
           }
       }
       stage("Test"){
           steps{
                   dir("simple-java-maven-app") {
                       sh "mvn test"
               }
           }
       }
    }
}`

**Comment by NotMyFault** [comment]
Hey,

issues in this organization aren't monitored as much as other community channels are. I recommend using [the forums](https://community.jenkins.io/) or the [jenkins](https://gitter.im/jenkinsci/jenkins) and [newcomer-contributions](https://gitter.im/jenkinsci/newcomer-contributors) chatroom.

Best,
Alex

**Comment by CPaxtonProgrammer** [comment]
Thanks, Alex. I'll check them out.

**Comment by NotMyFault** [comment]
We should add some organization-level templates to guide people to our common sources of communication and assistance, similar to jenkinsci or jenkins-infra.

If you don't mind and are able to create a `.github` repository in this organization, I can look into that @MarkEWaite.
I don't know who is part of this organization or manages things, so I'm just asking you 👀
