### ISSUE TITLE
Getting Maven version error while building the app in Jenkins

### ISSUE THREAD

**Issue by kargmad** [jenkins-docs/simple-java-maven-app#531]
Progress (5): 587 kB | 354 kB | 327 kB | 389 kB | 99 kB    
                                                       
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar (587 kB at 126 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-dependency-tree/3.1.1/maven-dependency-tree-3.1.1.jar (99 kB at 21 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.15/commons-codec-1.15.jar (354 kB at 74 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar (327 kB at 68 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache-extras/beanshell/bsh/2.0b6/bsh-2.0b6.jar (389 kB at 81 kB/s)
[[1;31mERROR[m] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.6.3 is not in the allowed range [3.8.6,).
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  01:15 min
[[1;34mINFO[m] Finished at: 2023-02-09T19:14:22Z
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m

**Comment by rinoy2002** [comment]
Fork the repository and change the line 60 of `pom.xml` file to `<version>[3.6.3,)</version>`

**Comment by kargmad** [comment]
Resolved.
