### ISSUE TITLE
Open Source License to reuse the examples?

### ISSUE THREAD

**Issue by mkurzman** [jenkins-docs/simple-java-maven-app#955]
Hi,
we would like to re-use your examples for tests and showcases in our OpenChain Automation Workgroup.
Would you be willing to share the examples under an Open Source license (maybe also the others for Python etc.)?
That would save us a lot of time.
Thank you.

**Comment by NOFAXKING** [comment]
ok no problem

**Comment by Eyegor2732** [comment]
Sure

**Comment by mkurzman** [comment]
Shall I do a PR with e.g. a MIT-license or will you add a license directly to the repo?
Thank you.

**Comment by gounthar** [comment]
I would say go ahead with a PR then.
Thanks a lot.

**Comment by gounthar** [comment]
Fixed by #1003.

Thanks a lot.
